SHELL=/bin/bash

.PHONY: all build

build:
	docker build --pull -t politician/ftb-horizons2:latest .

push:
	docker push politician/ftb-horizons2

sh:
	docker run --rm -it politician/ftb-horizons2



